language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_SDK_ROOT=/opt/android
    - ADB_INSTALL_TIMEOUT=10

before_install:
  - mkdir -p $ANDROID_SDK_ROOT
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;26.0.1" "extras;android;m2repository"
  - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
  - export QEMU_AUDIO_DRV=none

before_script:
  - cp -r licenses $ANDROID_HOME/
  - sdkmanager "system-images;android-21;google_apis;armeabi-v7a"
  - echo no | $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd --force -n test -k "system-images;android-21;google_apis;armeabi-v7a"
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - $ANDROID_HOME/tools/emulator -avd test -no-audio -no-window -netfast &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean assemble testDebugUnitTest connectedAndroidTest
#  - ./gradlew --info connectedCheck
#  - ./gradlew testDebugUnitTest

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
