version: 2.1

executors:
  default:
    docker:
      - image: circleci/android:api-28
    working_directory: ~/Kotlin-Espresso-sample

commands:
  restore_caches:
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle"}}

jobs:
  checkout:
    executor: default
    steps:
      - checkout
      - save_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/Kotlin-Espresso-sample

  dependencies:
    executor: default
    steps:
      - restore_caches
      - run: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle"}}
          paths:
            - ~/.gradle
            - ~/.m2

  unit_test:
    executor: default
    steps:
      - restore_caches
      - run:
          name: Run unit tests
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  inst_test:
    executor: default
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - restore_caches
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Waiting for emulator
          command: |
              circle-android wait-for-boot
              sleep 30
              adb shell input keyevent 82
              adb shell svc power stayon true
              adb shell settings put global window_animation_scale 0
              adb shell settings put global transition_animation_scale 0
              adb shell settings put global animator_duration_scale 0
      - run:
          name: Run UI tests
          command: ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - unit_test:
          requires:
            - dependencies
# Test using emulator is not supported on CircleCI2
# https://support.circleci.com/hc/en-us/articles/360000028928-Testing-with-Android-emulator-on-CircleCI-2-0
#      - inst_test:
#         requires:
#           - dependencies
